### ISSUE TITLE
Whenever I include it in my gulp-sass project, "error reading values after not"

### ISSUE THREAD

**Issue by ManasN** [danielguillan/modernizr-mixin#14]
Hi, very handy and nice plugin, thanks for that :).
I wonder why I my gulp-sass keeps giving me error whenever I @import "modernizr"; in my project's main.scss file.
It says "error reading values after not".

I am using gulp-sass which is wrapper for node-sass and which is based on libsass.

**Comment by ManasN** [comment]
oh, I think it's because of libsass' lack of support for "&(s)" Any workaround? 
I can't use Compass since I tried it in last project and compile times were as high as 20s/save.

**Comment by ManasN** [comment]
Okay, I just switched to "gulp-ruby-sass" and same error persists.

**Comment by danielguillan** [comment]
Thanks @ManasN! 

You're right, libsass doesn't support Sass 3.4 parent selector implementation yet (sass/libsass#548). That's why you're getting the error `reading values after not`.

It should work with Ruby Sass though. Compass is completely optional. Please, make sure you're using an up-to-date version of gulp-ruby-sass that uses at least Sass 3.4.

**Comment by ManasN** [comment]
Thanks daniel :)

**Comment by dawidvdh** [comment]
Hi Daniel, Great Mixin! i have however recently switched to a libsass project, and i am experiencing the same issues mentioned above. Is there anyway this could be slightly altered to work within libsass?

**Comment by danielguillan** [comment]
Thanks @dawidvdh! :)

Unfortunately we'll have to wait for libsass 3.2. The release is just around the corner: sass/libsass/issues/1020.

**Comment by danielguillan** [comment]
Hey guys, as you may already know, Libsass 3.2 has been released. I've pushed a new beta version of the Modernizr mixin with support for Libsass. If you want to give it a try you can find it here: https://github.com/danielguillan/modernizr-mixin/tree/v3.0.5-beta.1.

**Comment by johnpuddephatt** [comment]
:+1: looking forward to trying this!
