### ISSUE TITLE
Libsass

### ISSUE THREAD

**Issue by christianmagill** [danielguillan/modernizr-mixin#20]
Any chance of Libsass support?

**Comment by danielguillan** [comment]
Sorry, we'll have to wait for Libsass 3.2. It's just around the corner with only one remaining issue to be closed before it is released. (See #14)

**Comment by danielguillan** [comment]
Hey @christianmagill, as you may already know, Libsass 3.2 has been released. I've pushed a new beta version of the Modernizr mixin with support for Libsass. If you want to give it a try you can find it here: https://github.com/danielguillan/modernizr-mixin/tree/v3.0.5-beta.1.

**Comment by christianmagill** [comment]
Much thanks! Will do.
