### ISSUE TITLE
Add Eyeglass support.

### ISSUE THREAD

**Issue by sobolevn** [danielguillan/modernizr-mixin#22]
Is it a good idea to support [Eyeglass](https://github.com/sass-eyeglass/eyeglass)?

**Comment by danielguillan** [comment]
Sure! I haven't tried Eyeglass yet, but once I have time to play with it I'll add support. A pull request for this would be very welcome too!

**Comment by sobolevn** [comment]
Ok. I have made several changes to the project, but I am not submiting a pull-request by now. There are several things to add (like `npm` index) that is required. Also, I have a few questions considering code style and other things, which are not covered in `readme` or `contributing`. We can continue our discution in private, just email me: `mail@sobolevn.me`. Also, check out changes [here](https://github.com/sobolevn/modernizr-mixin).

Small change log: 
* Version updated to 3.0.6 (`bower.json`, `package.json`, `changelog.md`)
* `package.json` and `.npmignore` files created
* `eyeglass-exports.js` file added
* `.gitattributes` file added and `.gitignore` file updated
* mocha test added.

**Comment by danielguillan** [comment]
Thanks @sobolevn!

I think we can continue the conversation on this thread. It could benefit many people and also those who are familiar with Eyeglass can contribute with their knowledge.

Please, feel free to ask any questions you may have.

I have a few questions too:
1. Why do we need the `.gitattributes`file? Isn't this a preference that you may want to store globally in your configuration instead that on a per-project basis?
2. I don't like to have a huge `.gitignore` file. I want to have things specific to the project like sass-cache folders, node_modules, … but not things that we ignore all the time like OS and IDE specific files.
3. I'm planing to move my tests to [True](http://www.ericsuzanne.com/true/) with Mocha and get rid of the Ruby/Compass dependency. I see that you're using Mocha for the Eyeglass tests.

**Comment by danielguillan** [comment]
Thanks @sobolevn!

I think we can continue the conversation on this thread. It could benefit many people and also those who are familiar with Eyeglass can contribute with their knowledge.

Please, feel free to ask any questions you may have.

I have a few questions too:

1. Why do we need the `.gitattributes`file? Isn't this a preference that you may want to store globally in your configuration instead of on a per-project basis?
2. I don't like to have a huge `.gitignore` file. I want to have things specific to the project like `sass-cache` folders, `node_modules`, … but not things that we ignore all the time like OS and IDE specific files.
3. I'm planing (#21) to move my tests to [True](http://www.ericsuzanne.com/true/) with Mocha and get rid of the Ruby/Compass dependency. I see that you're using Mocha for the Eyeglass tests. Can we combine both tests easily in the future?

**Comment by sobolevn** [comment]
1.  My opinion is that "Explicit is better than implicit" on this one. But surely this file can be easily removed from the project.
2. The same here, I will refactor both files for only important files (assuming everything else is ignored on the global-level). 
3. Yes, I think so. But I haven't really tried `True` tests.

Should I remove `.gitattributes` and refactor both `.ignore` files?

My question was:
1. Do you have any `jshint`-like style guide for Javascript files? I guess you will need one, if you are migrating to `True + Mocha`. 
2. Does everything else look good to you? 

TODO list:
1. Edit `.travis.yml` to run both tests. (I don't know Ruby, I am not sure that I will configure it properly). Something like [that](http://stackoverflow.com/questions/18456611/is-it-possible-to-set-up-travis-to-run-tests-for-several-languages).
2. Register and upload `npm` package.

**Comment by danielguillan** [comment]
> Should I remove .gitattributes and refactor both .ignore files?

Yes please. I totally see your point but I still prefer to only add project-related files and folders to `.gitignore`.

Regarding your questions:
1. Feel free to use JSHint as the style guide.
2. Everything else looks good to me.

We should also update the README file with instructions on how to install the Modernizr mixin with Eyeglass.

I'll take care of registering and pushing the package to `npm` once I merge your pull request.

Thanks!

**Comment by danielguillan** [comment]
@sobolevn can you confirm you're getting the correct output? I see incorrect output when compiling from  both, Eyeglass and Libsass standalone. It might be related to this Libsass issue: sass/libsass#1210. The weird thing is that i did not encounter this error when I first updated the mixin to support Libsass at the time 3.2 was released.

**Comment by sobolevn** [comment]
`npm`'s `package.json` is missing `dependencies` and `devDependencies`. I was not able to run tests there. I haven't met this error before for some reason. What have I done:

1. I have tryied SassMeister on the libsass#1210 issue. The output was incorect. [Here](https://gist.github.com/sobolevn/66344275c6afcf684e2f) is the gist.

2. I have built new project named `test` with the following setup:

```bash
npm init
... [prompts] ...
npm install --save-dev node-sass eyeglass modernizr-mixin
mkdir test # and manually copied eyeglass tests there
npm test
``` 

The first test worked, so I have added 2 extra tests with this issue. There are the same as in the gist.
One passed, two failed. Full stack: 

```
 Eyeglass module testing
    ✓ should compile a sass file (167ms)
    1) sould not create an extra parent selector
    2) sould not create an extra parent selector with modernizr-mixin


  1 passing (307ms)
  2 failing

  1) Eyeglass module testing sould not create an extra parent selector:

      Uncaught AssertionError: '.foo *, .foo *:before, .foo *:after {\n  box-sizing: inherit;\n}\n' == '.foo .foo *, .foo .foo *:before, .foo .foo *:after {\n  box-sizing: inherit;\n}\n'
      + expected - actual

      -.foo *, .foo *:before, .foo *:after {
      +.foo .foo *, .foo .foo *:before, .foo .foo *:after {
         box-sizing: inherit;
       }
      
      at Object.callback (test/test_eyeglass.js:35:14)

  2) Eyeglass module testing sould not create an extra parent selector with modernizr-mixin:

      Uncaught AssertionError: '.js.svg .bar {\n  widht: 10px;\n}\n.no-js .bar, .no-svg .bar {\n  display: none;\n}\n' == '.bar .js.svg .bar {\n  widht: 10px;\n}\n\n.bar .no-js .bar, .bar .no-svg .bar {\n  display: none;\n}\n'
      + expected - actual

      -.js.svg .bar {
      +.bar .js.svg .bar {
         widht: 10px;
       }
      -.no-js .bar, .no-svg .bar {
      +
      +.bar .no-js .bar, .bar .no-svg .bar {
         display: none;
       }
      
      at Object.callback (test/test_eyeglass.js:35:14)



npm ERR! Test failed.  See above for more details.
```

**Comment by danielguillan** [comment]
I've tested with different versions of Libsass. Everything seems to work with versions 3.2.0 through 3.2.2.
It looks like a bug was introduced in Libsass 3.2.3 or 3.2.4. I've just commented on the issue: https://github.com/sass/libsass/issues/1210#issuecomment-108280019

**Comment by danielguillan** [comment]
I'm closing this issue and opening a new one (#24) for tracking the problem as it is not related to the Eyeglass implementation.

Thank you very much for the great work!
