### ISSUE TITLE
Incorrect selector output with Libsass 3.2.3 - 3.2.5

### ISSUE THREAD

**Issue by danielguillan** [danielguillan/modernizr-mixin#24]
A bug was introduced in Libsass 3.2.3. It makes the Modernizr mixin output the wrong selector.

Example:
``` scss
.selector { @include yep(csstransforms) { … }
```

Incorrectly compiles to:
``` css
.selector .csstransforms .selector { … }
```

Instead of:
```scss
.csstransforms .selector { … }
```

[The issue](sass/libsass#1210) has been fixed and will be available this [~~August~~ September?](https://github.com/sass/libsass/issues/1210#issuecomment-119624238) with the release of [Libsass 3.3](https://github.com/sass/libsass/milestones/3.3).

In the meantime, the only possible workaround is to use Libsass 3.2.2 to compile our code.

**Comment by mikestecker** [comment]
I keep having this error popup and the effect of it even though my system is telling me that I have libsass 3.2.2 installed. Could my system have a newer version installed and I cannot find it?

I'm on OS X El Capitan beta, libsass is NOT installed with Homebrew. As far as I can tell, it's only installed via node-sass, which my node-sass version is manually set at 3.0.0 and installed globally. libsass tells me it's version 3.2.2.

```zsh
# brew info libsass                                                    
libsass: stable 3.2.5, HEAD
C implementation of a Sass compiler
https://github.com/sass/libsass
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsass.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
```

```zsh
node-sass -v
node-sass	3.0.0	(Wrapper)	[JavaScript]
libsass  	3.2.2	(Sass Compiler)	[C/C++]
```
