### ISSUE TITLE
Add option to disable .no-js selector

### ISSUE THREAD

**Issue by borys-p** [danielguillan/modernizr-mixin#30]
I'm using your mixin to handle missing flexbox support. I use flexbox normally and add a special case with `@nope(flexbox)`. It works great, but fails in browsers with disabled javascript (eg. NoScript users will see the fallback layout). I'd love to have a way to disable the `.no-js` selector for this special case.

**Comment by borys-p** [comment]
Hey, why it was closed without any comment? The question is still valid.

**Comment by danielguillan** [comment]
Sorry for the lack of updates. This repository is no longer maintained and is being archived.
